name    'camptocamp-python'
version '0.0.1'
source 'https://github.com/camptocamp/puppet-python'
author 'DevOps Team / Camptocamp'
license 'GNU GPLv3'
summary 'Camptocamp Python Module'
description 'Python Module for Puppet'
project_page 'https://github.com/camptocamp/puppet-python'
